name: Build/release

on:
  push:
    tags:
    - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v1

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build/release Electron app
      uses: samuelmeuli/action-electron-builder@v1
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        release: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: Upload Artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: out
